//! What the shared tactics know about particular cards beyond their printed
//! stats: battles they cannot lose, what becomes of a monster that attacks
//! them, effects that cannot reach them, what their owner gets back when
//! they are destroyed.  Every deck plays around them by default; a deck that
//! wants the exception still decides it in its own `Strategy` hooks.
//!
//! The facts come from two places.  `pool.rs` is generated by `policy-bench
//! knowledge`: it stages every monster of the card pool on a plain board,
//! has it attacked, aimed at and attacking, and writes down what the engine
//! did.  The entries in [`facts`] are written by hand, for what a staged
//! board does not show: effects that depend on a coin toss, on the hand or
//! on another card.
//!
//! Facts are looked up by the code the viewer sees (`Ctx::facts`).  The
//! opponent's face-down cards have no code (the seat redacts them before the
//! policy looks), so nothing about a hidden card leaks: it stays an unknown
//! monster until it is flipped or revealed.

mod pool;

pub const THE_FOOL: u32 = 62892347;
pub const INFERNITY_GUARDIAN: u32 = 51566770;
pub const MORPHTRONIC_BOARDEN: u32 = 48381268;
pub const SET_MORPHTRONIC: u16 = 0x26;
pub const MORPHTRONIC_CAMERAN: u32 = 28124263;
pub const BIRDFACE: u32 = 45547649;
pub const MORPHTRONIC_BOOMBOXEN: u32 = 92720564;
pub const TOON_WORLD: u32 = 15259703;
pub const TOON_KINGDOM: u32 = 43175858;
pub const SET_TOON: u16 = 0x62;
pub const SET_FABLED: u16 = 0x35;
pub const FABLED_UNICORE: u32 = 44155002;
pub const SET_GUSTO: u16 = 0x10;
pub const DAIGUSTO_SPHREEZ: u32 = 29552709;
pub const GUSTO_GULLDO: u32 = 65277087;
pub const GUSTO_EGUL: u32 = 91662792;
pub const GUSTO_WINDA: u32 = 54455435;
pub const MACRO_COSMOS: u32 = 30241314;
pub const DIMENSIONAL_FISSURE: u32 = 81674782;
pub const BANISHER_OF_THE_RADIANCE: u32 = 94853057;
pub const DD_SURVIVOR: u32 = 48092532;
pub const DD_SCOUT_PLANE: u32 = 3773196;

/// Skill Drain: while it is face-up, monsters on the field have no effects.
pub const SKILL_DRAIN: u32 = 82732705;

/// Toon World by name: Toon Kingdom is treated as it while in the Field Zone.
pub const TOON_WORLDS: &[u32] = &[TOON_WORLD, TOON_KINGDOM];

/// "Every time", where a fact counts times in a turn.
pub const ALWAYS: u8 = u8::MAX;

/// Kinds of card whose effect is used on a monster, as a mask.
pub mod kind {
    pub const SPELL: u8 = 1;
    pub const TRAP: u8 = 2;
    pub const MONSTER: u8 = 4;
    pub const ALL: u8 = 7;
}

/// The attackers a fact holds against.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Against {
    #[default]
    All,
    /// Attackers with at least this much ATK.
    AttackFrom(i32),
    /// Attackers with less ATK than this.
    AttackBelow(i32),
    /// Attackers of at least this Level.
    LevelFrom(u8),
    /// Attackers below this Level.
    LevelBelow(u8),
    /// Attackers of these Attributes (the card database's bits).
    Attributes(u8),
}

impl Against {
    pub fn holds(self, attack: i32, level: u32, attribute: u32) -> bool {
        match self {
            Against::All => true,
            Against::AttackFrom(n) => attack >= n,
            Against::AttackBelow(n) => attack < n,
            Against::LevelFrom(n) => level >= n as u32,
            Against::LevelBelow(n) => level < n as u32,
            Against::Attributes(mask) => attribute & mask as u32 != 0,
        }
    }
}

/// What becomes of a monster.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Fate {
    #[default]
    Unharmed,
    Destroyed,
    Banished,
    /// To the hand or the Deck.
    Returned,
}

/// What a monster does to its attacker's ATK at damage calculation.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum AtkChange {
    #[default]
    None,
    Zero,
    Halved,
    Minus(i32),
}

impl AtkChange {
    pub fn apply(self, attack: i32) -> i32 {
        match self {
            AtkChange::None => attack,
            AtkChange::Zero => 0,
            AtkChange::Halved => (attack + 1) / 2,
            AtkChange::Minus(n) => (attack - n).max(0),
        }
    }
}

/// Damage the attacking player takes on top of the battle's own.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Burn {
    #[default]
    None,
    Fixed(i32),
    /// As much as the attacker's ATK.
    AttackerAtk,
    /// The battle damage its controller would have taken.
    Reflected,
}

/// What an attack on a face-up monster meets, in one battle position.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Attacked {
    /// Battles a turn that do not destroy it though they should.
    pub survives: u8,
    /// Attacks a turn its controller can negate, and the Life Points each costs.
    pub negates: u8,
    pub negate_cost: i32,
    /// What becomes of the attacker, whatever the battle's result.
    pub attacker: Fate,
    /// ...before damage calculation: there is no battle, and no damage.
    pub before_damage: bool,
    /// It leaves the field along with the attacker.
    pub leaves: bool,
    /// ...and only when the battle destroys it (Newdoria), not whenever it
    /// battles (D.D. Warrior Lady).
    pub when_destroyed: bool,
    /// Change of its battle stat at damage calculation.
    pub stat: i32,
    pub attacker_atk: AtkChange,
    /// Its controller takes no battle damage.
    pub no_damage: bool,
    pub burn: Burn,
    /// Roughly what its controller gets back when the battle destroys it: a
    /// monster from the Deck, a card to the hand, tokens.
    pub payoff: i32,
    /// Other cards the attacking player loses then; [`ALWAYS`]: every monster.
    pub collateral: u8,
    /// Changes battle position when attacked.  The rest describes the
    /// position it ends up in.
    pub switches: bool,
    /// The attackers all of this holds against; others meet a plain monster.
    pub against: Against,
}

impl Attacked {
    pub const PLAIN: Attacked = Attacked {
        survives: 0,
        negates: 0,
        negate_cost: 0,
        attacker: Fate::Unharmed,
        before_damage: false,
        leaves: false,
        when_destroyed: false,
        stat: 0,
        attacker_atk: AtkChange::None,
        no_damage: false,
        burn: Burn::None,
        payoff: 0,
        collateral: 0,
        switches: false,
        against: Against::All,
    };
}

/// What a monster's own attack on a monster does.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Striking {
    /// ATK it gains in the Damage Step.
    pub bonus: i32,
    /// Inflicts piercing battle damage.
    pub piercing: bool,
    /// Can attack directly past the opponent's monsters.
    pub direct: bool,
    /// What becomes of the monster it attacks, whatever the battle's result.
    pub target: Fate,
    /// ...before damage calculation: there is no battle, and no damage.
    pub before_damage: bool,
    /// It leaves the field along with its target.
    pub leaves: bool,
    /// The targets `target` holds against, by their ATK, Level or Attribute.
    pub against: Against,
}

impl Striking {
    pub const PLAIN: Striking = Striking {
        bonus: 0,
        piercing: false,
        direct: false,
        target: Fate::Unharmed,
        before_damage: false,
        leaves: false,
        against: Against::All,
    };
}

/// What the facts about being attacked or destroyed depend on.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub enum Needs {
    #[default]
    Nothing,
    /// Its controller has no cards in hand (Infernity Guardian).
    EmptyHand,
    /// Unicore only negates while both players have the same hand size.
    EqualHands,
}

/// Facts about one card, as long as it is face-up.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Facts {
    /// Attacked in Attack Position, and in Defense Position.
    pub attacked: [Attacked; 2],
    /// What `attacked`, `immune` and `unaffected` depend on.
    pub needs: Needs,
    /// Its own attacks.
    pub striking: Striking,
    /// Kinds of effect that cannot target it.
    pub untargetable: u8,
    /// Kinds of effect its controller negates, whatever they do, at no cost.
    pub negates_any: u8,
    /// Kinds of effect its controller negates when they target it, and it
    /// stays on the field.
    pub negates_aimed: u8,
    /// Kinds of effect its controller negates when they would destroy it,
    /// targeting it or not, and it stays on the field.
    pub negates_destruction: u8,
    /// How many times a turn it negates.
    pub negate_times: u8,
    /// Each negation costs its controller a card from the hand.
    pub negate_discards: bool,
    /// Kinds of effect that cannot destroy it.
    pub immune: u8,
    /// Kinds of effect that do nothing to it.
    pub unaffected: u8,
    /// Roughly what its controller gets back when an effect destroys it.
    pub effect_payoff: i32,
    /// Other cards the player destroying it loses then; [`ALWAYS`]: every monster.
    pub effect_collateral: u8,
    /// Its coin decides whose effects that target it are negated and
    /// destroyed: heads its controller's, tails the opponent's (The Fool).
    pub coin_targeting_shield: bool,
}

impl Facts {
    pub const NONE: Facts = Facts {
        attacked: [Attacked::PLAIN; 2],
        needs: Needs::Nothing,
        striking: Striking::PLAIN,
        untargetable: 0,
        negates_any: 0,
        negates_aimed: 0,
        negates_destruction: 0,
        negate_times: 0,
        negate_discards: false,
        immune: 0,
        unaffected: 0,
        effect_payoff: 0,
        effect_collateral: 0,
        coin_targeting_shield: false,
    };

    /// The same in both battle positions.
    pub const fn attacked(attacked: Attacked) -> Facts {
        Facts { attacked: [attacked; 2], ..Facts::NONE }
    }
}

/// What the probes showed about a card of the pool.
pub fn probed(code: u32) -> Option<Facts> {
    pool::POOL.binary_search_by_key(&code, |(c, _)| *c).ok().map(|i| pool::POOL[i].1)
}

/// What we know about the card with this (canonical) code: what the probes
/// showed, and on top of it what they cannot.
pub fn facts(code: u32) -> Facts {
    const PLAIN: Attacked = Attacked::PLAIN;
    let mut facts = probed(code).unwrap_or(Facts::NONE);
    match code {
        // The coin is tossed when it is Summoned.
        THE_FOOL => facts.coin_targeting_shield = true,
        // Only with no cards in hand.
        INFERNITY_GUARDIAN => {
            facts.needs = Needs::EmptyHand;
            facts.attacked = [Attacked { survives: ALWAYS, ..PLAIN }; 2];
            facts.immune = kind::ALL;
        }
        // Its trigger needs a "Harpie Lady" in the Deck, a Morphtronic in
        // the hand or Graveyard: the staged Deck has neither.
        BIRDFACE => facts.attacked = [Attacked { payoff: 700, ..PLAIN }; 2],
        MORPHTRONIC_CAMERAN => facts.attacked[0].payoff = 1000,
        FABLED_UNICORE => {
            // The probe's particular hand sizes cannot establish an unconditional lock.
            facts = Facts { needs: Needs::EqualHands, negates_any: kind::ALL,
                negate_times: ALWAYS, ..Facts::NONE };
        }
        GUSTO_GULLDO | GUSTO_EGUL | GUSTO_WINDA => {
            // The probe's generic Deck contains no Gusto to recruit.
            facts.attacked = [Attacked { payoff: 1100, ..PLAIN }; 2];
            if code == GUSTO_GULLDO { facts.effect_payoff = 1100; }
        }
        _ => {}
    }
    facts
}

/// What a card is worth to the deck that plays it, as that deck's own policy
/// rates it (its `Strategy::value`): the Spells/Traps that stay on the field
/// and that a deck runs on (Toon World, Necrovalley, Gateway of the Six...),
/// and the monsters it values above their printed stats.  Seen face-up on
/// the opponent's field, such a card is one to remove first.  0 for the rest.
pub fn owner_worth(code: u32) -> i32 {
    match code {
        88307361 => 3400, // Coelacanth: mass Fish recruitment
        53257892 => 2800, // Gigaplant: Plant/Insect revival
        95750695 => 2100, // Supervise: Gemini effects and revival
        44665365 => 3500, // Herald of Perfection: renewable negation
        59509952 => 3300, // Archlord Kristya: Special Summon restriction
        55794644 => 3100, // Master Hyperion: repeatable removal
        17259470 | 70595331 => 2300, // Zombie Master / Il Blud: revival engines
        DAIGUSTO_SPHREEZ => 3400, // protects the Gusto battle plan
        FABLED_UNICORE => 2700,
        MACRO_COSMOS | DIMENSIONAL_FISSURE => 2600,
        32296881 => 2600, // Bountiful Artemis: draws for Counter Traps
        49905576 => 2400, // Meltiel: LP and removal after Counter Traps
        56433456 => 2200, // Sanctuary enables Divine Punishment and Meltiel
        52687916 => 3300, // Trishula, Dragon of the Ice Barrier (quickdraw-plant)
        15259703 | // Toon World (toon)
        79229522 => 3000, // Chimeratech Fortress Dragon (machina)
        82732705 => 2800, // Skill Drain (rock-block)
        75782277 | // Harpies' Hunting Ground (harpie)
        53569894 | // Pyramid of Light (pyramid)
        83965310 | // Destiny HERO - Plasma (destiny-hero)
        64752646 | // Fire Princess (burn)
        3825890 => 2600, // Gravekeeper's Visionary (gravekeeper)
        27970830 | // Gateway of the Six (six-samurai)
        47355498 => 2500, // Necrovalley (gravekeeper)
        39910367 => 2400, // Magical Citadel of Endymion (spellcaster)
        34487429 | // Ancient City - Rainbow Ruins (crystal)
        62265044 => 2300, // Dragon Ravine (dragunity)
        3657444 | // Cyber Valley (countdown)
        51481927 => 2200, // Spell Absorption (burn)
        66957584 | // Infernity Launcher (infernity)
        82971335 => 2100, // Fortune Lady Earth (fortune-lady)
        33550694 | // Fusion Gate (heroes)
        90011152 | // Ojama Country (ojama)
        86780027 | // Solidarity (arcana)
        55586621 | // Fortune Lady Dark (fortune-lady)
        6924874 | // Harpie's Pet Baby Dragon (harpie)
        86197239 | // Infernity Mirage (infernity)
        55119278 | // Morphtronic Radion (morphtronic)
        64631466 => 2000, // Relinquished (toon)
        63730624 | // Double Tool C&D (morphtronic)
        61962135 | // Glorious Illusion (lightsworn)
        85101228 | // Morphtronic Bind (morphtronic)
        38992735 | // Wave-Motion Cannon (burn)
        54578613 | // Dragunity Legionnaire (dragunity)
        95503687 => 1900, // Lumina, Lightsworn Summoner (lightsworn)
        59755122 => 1850, // Dragunity Phalanx (dragunity)
        77778835 | // Hysteric Party (harpie)
        72345736 | // Six Samurai United (six-samurai)
        32710364 | // Crystal Beast Ruby Carbuncle (crystal)
        28355718 | // Destiny HERO - Double Dude (destiny-hero)
        82693917 | // Fortune Lady Wind (fortune-lady)
        5975022 | // Gladiator Beast Murmillo (gladiator)
        49080532 | // Infernity Beetle (infernity)
        37132349 => 1800, // Ojama Red (ojama)
        47408488 | // Crystal Tree (crystal)
        93016201 | // Royal Oppression (rock-block)
        29088922 => 1700, // Fortune Lady Water (fortune-lady)
        81896771 => 1650, // Wattpheasant (watt)
        22751868 | // Karakuri Showdown Castle (karakuri)
        36870345 | // Dragunity Aklys (dragunity)
        81962318 | // Dragunity Tribus (dragunity)
        71870152 => 1600, // Fortune Lady Fire (fortune-lady)
        91351370 | // Black Whirlwind (blackwing)
        77565204 | // Future Fusion (heroes)
        85541675 | // Karakuri Anatomy (karakuri)
        56074358 | // Morphtronic Map (morphtronic)
        90239723 | // Morphtronic Repair Unit (morphtronic)
        15341821 | // Dandylion (quickdraw-plant)
        41613948 | // Destiny HERO - Doom Lord (destiny-hero)
        9411399 | // Destiny HERO - Malicious (destiny-hero)
        34471458 | // Fortune Lady Light (fortune-lady)
        45141844 | // Old Vindictive Magician (spellcaster)
        92373006 | // Test Tiger (gladiator)
        98777036 => 1500, // Tragoedia (monarch)
        85087012 | // Card Trooper (quickdraw-plant)
        2326738 | // Des Lacooda (pyramid)
        67441435 | // Glow-Up Bulb (quickdraw-plant)
        29947751 | // Morphtronic Magnen (morphtronic)
        23205979 | // Spirit Reaper (pyramid)
        11747708 => 1400, // Spore (quickdraw-plant)
        19665973 | // Battle Fader (monarch)
        54455664 | // Dragunity Brandistock (dragunity)
        33420078 | // Plaguespreader Zombie (tele-dad)
        21502796 | // Ryko, Lightsworn Hunter (lightsworn)
        33883834 => 1300, // Shien's Squire (six-samurai)
        82099401 | // Crystal Seer (spellcaster)
        55461064 | // Destiny HERO - Blade Master (destiny-hero)
        57421866 | // Level Eater (quickdraw-plant)
        78349103 | // Machina Peacekeeper (machina)
        65685470 | // Spirit of the Six Samurai (six-samurai)
        24996659 => 1200, // Wattkiwi (watt)
        5554990 | // Wattberyx (watt)
        96099959 => 1100, // X-Saber Palomuro (x-saber)
        85475641 | // Infernity Avenger (infernity)
        93542102 | // Morphtronic Celfon (morphtronic)
        32548609 => 1000, // Wattmole (watt)
        23093604 => 900, // X-Saber Pashuul (x-saber)
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `probed` searches the table by code.
    #[test]
    fn the_pool_table_is_sorted_by_code() {
        assert!(pool::POOL.windows(2).all(|w| w[0].0 < w[1].0));
        assert!(pool::POOL.iter().all(|(_, facts)| *facts != Facts::NONE));
    }

    #[test]
    fn conditions_on_the_attacker() {
        assert!(Against::All.holds(0, 0, 0));
        assert!(Against::AttackFrom(1900).holds(1900, 4, 1) && !Against::AttackFrom(1900).holds(1800, 4, 1));
        assert!(Against::LevelBelow(8).holds(1000, 7, 1) && !Against::LevelBelow(8).holds(1000, 8, 1));
        // Every Attribute but DARK (0x20).
        assert!(Against::Attributes(0x1f).holds(0, 0, 0x10) && !Against::Attributes(0x1f).holds(0, 0, 0x20));
    }
}
