//! Generated by `policy-bench knowledge`; do not edit.
//!
//! What the engine did when each monster of `data/wc2011.lflist.conf` was staged
//! on a plain board and attacked, aimed at with a Spell, a Trap and a monster
//! effect, and made to attack: 2444 monsters probed, 344 with something to
//! know.  Regenerate it after changing the card scripts, the pool or the
//! probes; corrections go in `knowledge::facts`, not here.
#[allow(unused_imports)]
use super::{kind, Against, AtkChange, Attacked, Burn, Facts, Fate, Striking, ALWAYS};

const P: Attacked = Attacked::PLAIN;
const S: Striking = Striking::PLAIN;
const N: Facts = Facts::NONE;

/// Sorted by code.
#[rustfmt::skip]
pub(super) static POOL: &[(u32, Facts)] = &[
    // Miracle Flipper
    (131182, Facts { effect_collateral: 1, ..N }),
    // Key Mouse
    (135598, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Wattgiraffe
    (402568, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Cherry Inmato
    (525110, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Dark Mimic LV3
    (1102515, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Cyber End Dragon
    (1546123, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Ancient Gear Engineer
    (1953925, Facts { negates_aimed: kind::TRAP, negate_times: ALWAYS, ..N }),
    // Silent Swordsman LV3
    (1995985, Facts { negates_aimed: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Hyper Hammerhead
    (2671330, Facts { attacked: [Attacked { attacker: Fate::Returned, ..P }; 2], ..N }),
    // Wattchimera
    (2772236, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Servant of Catabolism
    (2792265, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Reflect Bounder
    (2851070, Facts { attacked: [Attacked { burn: Burn::AttackerAtk, ..P }, P], ..N }),
    // Naturia Barkion
    (2956282, Facts { negates_aimed: kind::TRAP, negate_times: 1, ..N }),
    // Alligator's Sword Dragon
    (3366982, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Cyber Phoenix
    (3370104, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], negates_aimed: kind::SPELL | kind::TRAP, negate_times: ALWAYS, ..N }),
    // Cyber Valley
    (3657444, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Karakuri Soldier mdl 236 "Nisamu"
    (3846170, Facts { attacked: [Attacked { switches: true, ..P }, Attacked { payoff: 1000, ..P }], ..N }),
    // Super Vehicroid - Stealth Union
    (3897065, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Newdoria
    (4335645, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, ..P }; 2], ..N }),
    // Yubel - Terror Incarnate
    (4779091, Facts { attacked: [Attacked { survives: ALWAYS, no_damage: true, burn: Burn::Reflected, ..P }, Attacked { survives: ALWAYS, ..P }], ..N }),
    // Neos Wiseman
    (5126490, Facts { attacked: [Attacked { burn: Burn::AttackerAtk, ..P }; 2], immune: kind::ALL, ..N }),
    // Elemental HERO Neo Bubbleman
    (5285665, Facts { attacked: [Attacked { attacker: Fate::Destroyed, ..P }; 2], ..N }),
    // Cyber Dragon Zwei
    (5373478, Facts { striking: Striking { bonus: 300, ..S }, ..N }),
    // Warrior Lady of the Wasteland
    (5438492, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Scarr, Scout of Dark World
    (5498296, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Machina Fortress
    (5556499, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, ..P }; 2], effect_collateral: 1, ..N }),
    // Arcana Knight Joker
    (6150044, Facts { negates_aimed: kind::MONSTER, negate_times: 1, negate_discards: true, ..N }),
    // Karakuri Ninja mdl 919 "Kuick"
    (6276588, Facts { attacked: [Attacked { switches: true, ..P }; 2], ..N }),
    // Koa'ki Meiru Boulder
    (6320631, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Aurkus, Lightsworn Druid
    (7183277, Facts { untargetable: kind::SPELL | kind::MONSTER, ..N }),
    // D.D. Warrior Lady
    (7572887, Facts { attacked: [Attacked { attacker: Fate::Banished, leaves: true, ..P }; 2], striking: Striking { target: Fate::Banished, leaves: true, ..S }, ..N }),
    // Phantom Beast Wild-Horn
    (7576264, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // UFOroid
    (7602840, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Vortex Trooper
    (7736719, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Vennominaga the Deity of Poisonous Snakes
    (8062132, Facts { untargetable: kind::SPELL | kind::MONSTER, immune: kind::SPELL, ..N }),
    // Blackwing - Fane the Steel Chain
    (9109991, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Apprentice Magician
    (9156135, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Jinzo - Returner
    (9418534, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Gyaku-Gire Panda
    (9817927, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Mecha Bunny
    (10110717, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Cyber Blader
    (10248389, Facts { negates_aimed: kind::MONSTER, negate_times: 1, ..N }),
    // T.A.D.P.O.L.E.
    (10456559, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Masked HERO Vapor
    (10920352, Facts { immune: kind::ALL, ..N }),
    // Lancer Dragonute
    (11125718, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Horus the Black Flame Dragon LV6
    (11224103, Facts { immune: kind::SPELL, unaffected: kind::SPELL, ..N }),
    // Gellenduo
    (11662742, Facts { attacked: [P, Attacked { survives: ALWAYS, ..P }], ..N }),
    // Fabled Ashenveil
    (12235475, Facts { attacked: [Attacked { stat: 600, ..P }, P], striking: Striking { bonus: 600, ..S }, ..N }),
    // Prime Material Dragon
    (12298909, Facts { negates_destruction: kind::ALL, negate_times: ALWAYS, negate_discards: true, ..N }),
    // Neo-Parshath, the Sky Paladin
    (12510878, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Ultimate Ancient Gear Golem
    (12652643, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Gem-Knight Aquamarine
    (13108445, Facts { attacked: [Attacked { attacker: Fate::Returned, when_destroyed: true, ..P }; 2], effect_collateral: 1, ..N }),
    // Cloudian - Storm Dragon
    (13474291, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // Dark Flare Knight
    (13722870, Facts { attacked: [Attacked { no_damage: true, ..P }, P], ..N }),
    // King Dragun
    (13756293, Facts { untargetable: kind::SPELL | kind::MONSTER, ..N }),
    // Exodius the Ultimate Forbidden Lord
    (13893596, Facts { striking: Striking { bonus: 1000, ..S }, ..N }),
    // Wall of Illusion
    (13945283, Facts { attacked: [Attacked { attacker: Fate::Returned, ..P }; 2], ..N }),
    // Gaia Plate the Earth Giant
    (14258627, Facts { attacked: [Attacked { attacker_atk: AtkChange::Halved, ..P }; 2], ..N }),
    // Archfiend Interceptor
    (14430063, Facts { attacked: [Attacked { burn: Burn::Fixed(500), ..P }, P], ..N }),
    // Gokipon
    (14472500, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Dandylion
    (15341821, Facts { attacked: [Attacked { payoff: 600, ..P }; 2], effect_payoff: 600, ..N }),
    // Tanngrisnir of the Nordic Beasts
    (15394083, Facts { attacked: [Attacked { payoff: 600, ..P }; 2], ..N }),
    // Amazoness Queen
    (15951532, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Cloudian - Turbulence
    (16197610, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // Cloudian - Acid Cloud
    (17810268, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // Airknight Parshath
    (18036057, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Gyroid
    (18325492, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Noble Knight Joan
    (18426196, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Gemini Summoner
    (19041767, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Cloudian - Nimbusman
    (20003527, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // Shark Cruiser
    (20358953, Facts { effect_payoff: 1000, ..N }),
    // Exploder Dragon
    (20586572, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, ..P }; 2], ..N }),
    // Pilgrim of the Ice Barrier
    (20700531, Facts { attacked: [Attacked { survives: ALWAYS, against: Against::AttackFrom(1900), ..P }; 2], ..N }),
    // Psychic Commander
    (21454943, Facts { attacked: [Attacked { attacker_atk: AtkChange::Minus(100), ..P }; 2], ..N }),
    // Gragonith, Lightsworn Dragon
    (21785144, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Evil HERO Inferno Wing
    (22160245, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Doctor Cranium
    (22171591, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Ally of Justice Unknown Crusher
    (22371016, Facts { attacked: [Attacked { attacker: Fate::Banished, against: Against::Attributes(16), ..P }; 2], ..N }),
    // Nimble Momonga
    (22567609, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Zeman the Ape King
    (22858242, Facts { attacked: [Attacked { negates: ALWAYS, ..P }; 2], ..N }),
    // Hyena
    (22873798, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // X-Saber Pashuul
    (23093604, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Spirit Reaper
    (23205979, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Phoenixian Cluster Amaryllis
    (23558733, Facts { attacked: [Attacked { burn: Burn::Fixed(800), ..P }; 2], ..N }),
    // Colossal Fighter
    (23693634, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Strong Wind Dragon
    (23770284, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Naturia White Oak
    (24644634, Facts { effect_payoff: 2000, ..N }),
    // Shooting Star Dragon
    (24696097, Facts { negates_destruction: kind::ALL, negate_times: 1, ..N }),
    // Light End Dragon
    (25132288, Facts { attacked: [Attacked { stat: -500, attacker_atk: AtkChange::Minus(1500), ..P }, P], ..N }),
    // Ally of Justice Garadholg
    (25771826, Facts { attacked: [Attacked { stat: 200, against: Against::Attributes(16), ..P }, P], ..N }),
    // Legendary Jujitsu Master
    (25773409, Facts { attacked: [P, Attacked { attacker: Fate::Returned, ..P }], ..N }),
    // Sanga of the Thunder
    (25955164, Facts { attacked: [Attacked { attacker_atk: AtkChange::Zero, ..P }; 2], ..N }),
    // Ancient Sacred Wyvern
    (25958491, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Vengeful Shinobi
    (26046205, Facts { attacked: [Attacked { payoff: 700, ..P }, P], ..N }),
    // Sangan
    (26202165, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Ally of Justice Catastor
    (26593852, Facts { attacked: [Attacked { attacker: Fate::Destroyed, before_damage: true, against: Against::Attributes(31), ..P }; 2], striking: Striking { target: Fate::Destroyed, before_damage: true, against: Against::Attributes(31), ..S }, ..N }),
    // Gladiator Beast Heraklinos
    (27346636, Facts { negates_aimed: kind::SPELL | kind::TRAP, negates_destruction: kind::SPELL, negate_times: ALWAYS, negate_discards: true, ..N }),
    // Shiba-Warrior Taro
    (27416701, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Secret Guards of the Ice Barrier
    (27527047, Facts { untargetable: kind::MONSTER, ..N }),
    // The Unhappy Girl
    (27618634, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // Flamvell Poun
    (28332833, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Shield Wing
    (28859794, Facts { attacked: [Attacked { survives: 2, ..P }; 2], ..N }),
    // Daigusto Sphreez
    (29552709, Facts { attacked: [Attacked { survives: ALWAYS, no_damage: true, burn: Burn::Reflected, ..P }, Attacked { survives: ALWAYS, ..P }], ..N }),
    // Amazoness Chain Master
    (29654737, Facts { attacked: [Attacked { payoff: 700, collateral: 1, ..P }; 2], ..N }),
    // Watthydra
    (29765339, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Legendary Six Samurai - Shi En
    (29981921, Facts { negates_aimed: kind::SPELL | kind::TRAP, negates_destruction: kind::SPELL, negate_times: 1, ..N }),
    // Karakuri Merchant mdl 177 "Inashichi"
    (30230789, Facts { attacked: [Attacked { switches: true, ..P }, P], ..N }),
    // Reese the Ice Mistress
    (30276969, Facts { attacked: [Attacked { survives: ALWAYS, against: Against::LevelFrom(4), ..P }; 2], ..N }),
    // Mad Reloader
    (31034919, Facts { attacked: [Attacked { payoff: 1400, ..P }; 2], ..N }),
    // Blackwing - Abrolhos the Megaquake
    (31053337, Facts { attacked: [Attacked { attacker: Fate::Returned, ..P }; 2], striking: Striking { target: Fate::Returned, ..S }, ..N }),
    // Marshmallon
    (31305911, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Spear Dragon
    (31553716, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Yubel - The Ultimate Nightmare
    (31764700, Facts { attacked: [Attacked { survives: ALWAYS, attacker: Fate::Destroyed, no_damage: true, burn: Burn::Reflected, ..P }, Attacked { survives: ALWAYS, ..P }], striking: Striking { target: Fate::Destroyed, ..S }, ..N }),
    // Dark Diviner
    (31919988, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Regenerating Rose
    (31986288, Facts { attacked: [Attacked { payoff: 600, ..P }; 2], ..N }),
    // Scrap Worm
    (32761286, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Jinzo #7
    (32809211, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Crystal Beast Amethyst Cat
    (32933942, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Naturia Beast
    (33198837, Facts { negates_any: kind::SPELL, negates_aimed: kind::SPELL, negates_destruction: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Blackwing - Silverwind the Ascendant
    (33236860, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Naturia Cliff
    (33866130, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], effect_payoff: 1000, ..N }),
    // Dash Warrior
    (34257001, Facts { striking: Striking { bonus: 1200, ..S }, ..N }),
    // Fortune Lady Light
    (34471458, Facts { effect_payoff: 1000, ..N }),
    // Cyber Larva
    (35050257, Facts { attacked: [Attacked { no_damage: true, payoff: 1000, ..P }, Attacked { payoff: 1000, ..P }], ..N }),
    // Darkbishop Archfiend
    (35798491, Facts { negates_aimed: kind::ALL, negate_times: ALWAYS, ..N }),
    // Jinzo - Lord
    (35803249, Facts { negates_any: kind::TRAP, negate_times: ALWAYS, ..N }),
    // Babycerasaurus
    (36042004, Facts { effect_payoff: 1000, ..N }),
    // Super Vehicroid Jumbo Drill
    (36256625, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Sonic Chick
    (36472900, Facts { attacked: [Attacked { survives: ALWAYS, against: Against::AttackFrom(1900), ..P }; 2], ..N }),
    // Ally of Justice Core Destroyer
    (36629203, Facts { attacked: [Attacked { attacker: Fate::Destroyed, before_damage: true, against: Against::Attributes(16), ..P }; 2], ..N }),
    // Castle Gate
    (36931229, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // D.D. Warrior
    (37043180, Facts { attacked: [Attacked { attacker: Fate::Banished, leaves: true, ..P }; 2], striking: Striking { target: Fate::Banished, leaves: true, ..S }, ..N }),
    // Hyper Psychic Blaster/Assault Mode
    (37169670, Facts { attacked: [Attacked { burn: Burn::Fixed(2000), ..P }; 2], ..N }),
    // Silent Swordsman LV7
    (37267041, Facts { negates_any: kind::SPELL, negates_aimed: kind::SPELL, negates_destruction: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Manga Ryu-Ran
    (38369349, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Pandaborg
    (39091951, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Karakuri Bushi mdl 6318 "Muzanichiha"
    (39118197, Facts { attacked: [Attacked { switches: true, ..P }, P], ..N }),
    // Masked Dragon
    (39191307, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Ultimate Axon Kicker
    (40101111, Facts { striking: Striking { piercing: true, ..S }, immune: kind::ALL, ..N }),
    // Twin-Sword Marauder
    (40225398, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Exploder Dragonwing
    (40529384, Facts { attacked: [P, Attacked { attacker: Fate::Destroyed, before_damage: true, against: Against::AttackBelow(2500), ..P }], ..N }),
    // Elemental HERO Absolute Zero
    (40854197, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, collateral: ALWAYS, ..P }; 2], effect_collateral: ALWAYS, ..N }),
    // Dai-sojo of the Ice Barrier
    (41090784, Facts { immune: kind::SPELL | kind::TRAP, ..N }),
    // Cyberdark Horn
    (41230939, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Rallis the Star Bird
    (41382147, Facts { striking: Striking { bonus: 800, ..S }, ..N }),
    // Elemental HERO Phoenix Enforcer
    (41436536, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Elemental HERO Darkbright
    (41517968, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, ..P }; 2], striking: Striking { piercing: true, ..S }, effect_collateral: 1, ..N }),
    // Naturia Butterfly
    (42110434, Facts { attacked: [Attacked { negates: 1, ..P }; 2], ..N }),
    // XX-Saber Emmersblade
    (42737833, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Reptilianne Gardna
    (43002864, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Cloudian - Cirrostratus
    (43318266, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // Jurrac Gallim
    (43332022, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, ..P }; 2], ..N }),
    // Armityle the Chaos Phantasm
    (43378048, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // The Fabled Unicore
    (44155002, Facts { negates_any: kind::TRAP, negates_aimed: kind::TRAP, negates_destruction: kind::MONSTER, negate_times: ALWAYS, ..N }),
    // Abyssal Kingshark
    (44223284, Facts { immune: kind::SPELL, ..N }),
    // Jade Knight
    (44364207, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], immune: kind::TRAP, ..N }),
    // Bitelon
    (44702857, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Steamroid
    (44729197, Facts { attacked: [Attacked { stat: -500, ..P }, P], striking: Striking { bonus: 500, ..S }, ..N }),
    // Naturia Beans
    (44789585, Facts { attacked: [Attacked { survives: 1, burn: Burn::Fixed(500), ..P }; 2], ..N }),
    // Ocean's Keeper
    (45045866, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Scarred Warrior
    (45298492, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Jurrac Ptera
    (45711266, Facts { attacked: [Attacked { attacker: Fate::Returned, ..P }; 2], ..N }),
    // Turbo Warrior
    (46195773, Facts { untargetable: kind::MONSTER, ..N }),
    // Lancer Lindwurm
    (46272804, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Mefist the Infernal General
    (46820049, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Light and Darkness Dragon
    (47297616, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], negates_aimed: kind::ALL, negates_destruction: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Gigantes
    (47606319, Facts { attacked: [Attacked { collateral: 1, ..P }; 2], ..N }),
    // Horus the Black Flame Dragon LV8
    (48229808, Facts { negates_any: kind::SPELL, negates_aimed: kind::SPELL, negates_destruction: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Grave Squirmer
    (48343627, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, ..P }; 2], ..N }),
    // Morphtronic Boarden
    (48381268, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Jurrac Stauriko
    (48411996, Facts { attacked: [Attacked { payoff: 600, ..P }; 2], ..N }),
    // Danipon
    (48588176, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Nova Summoner
    (48783998, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Blackwing - Bora the Spear
    (49003716, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Ultimate Insect LV1
    (49441499, Facts { immune: kind::SPELL, unaffected: kind::SPELL, ..N }),
    // Saber Beetle
    (49645921, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Freed the Matchless General
    (49681811, Facts { negates_aimed: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Ryu Senshi
    (49868263, Facts { negates_aimed: kind::SPELL | kind::TRAP, negate_times: ALWAYS, ..N }),
    // Evil HERO Infernal Sniper
    (50282757, Facts { immune: kind::SPELL, ..N }),
    // Archfiend of Gilfer
    (50287060, Facts { attacked: [Attacked { payoff: 500, ..P }; 2], effect_payoff: 500, ..N }),
    // Satellite Cannon
    (50400231, Facts { attacked: [Attacked { survives: ALWAYS, against: Against::LevelBelow(8), ..P }; 2], ..N }),
    // X-Saber Galahad
    (50604950, Facts { attacked: [Attacked { stat: -500, ..P }, P], striking: Striking { bonus: 300, ..S }, ..N }),
    // Stygian Security
    (50732780, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Different Dimension Dragon
    (50939127, Facts { immune: kind::SPELL, ..N }),
    // Gaia Soul the Combustible Collective
    (51355346, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Yomi Ship
    (51534754, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, ..P }; 2], ..N }),
    // Dread Dragon
    (51925772, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Rockstone Warrior
    (51987571, Facts { attacked: [Attacked { no_damage: true, ..P }, P], ..N }),
    // Obnoxious Celtic Guard
    (52077741, Facts { attacked: [Attacked { survives: ALWAYS, against: Against::AttackFrom(1900), ..P }; 2], ..N }),
    // Ally of Justice Rudra
    (52265835, Facts { attacked: [Attacked { stat: 700, against: Against::Attributes(16), ..P }, P], ..N }),
    // Black Veloci
    (52319752, Facts { attacked: [Attacked { stat: -400, ..P }, P], striking: Striking { bonus: 400, ..S }, ..N }),
    // Peten the Dark Clown
    (52624755, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], effect_payoff: 1000, ..N }),
    // Blackwing - Gust the Backblast
    (52869807, Facts { attacked: [Attacked { attacker_atk: AtkChange::Minus(300), ..P }; 2], ..N }),
    // Blue-Eyes Toon Dragon
    (53183600, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Fabled Dianaira
    (53199020, Facts { immune: kind::SPELL, ..N }),
    // Blue-Eyes Shining Dragon
    (53347303, Facts { negates_aimed: kind::ALL, negate_times: ALWAYS, ..N }),
    // Flamvell Uruquizas
    (53714009, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Kelbek
    (54878498, Facts { attacked: [Attacked { attacker: Fate::Returned, ..P }; 2], ..N }),
    // Amazoness Fighter
    (55821894, Facts { attacked: [Attacked { no_damage: true, ..P }, P], ..N }),
    // Unifrog
    (56052205, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Cloudian - Sheep Cloud
    (56597272, Facts { attacked: [Attacked { payoff: 600, ..P }; 2], ..N }),
    // Poison Draw Frog
    (56840658, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Luminous Soldier
    (57482479, Facts { attacked: [Attacked { stat: 500, against: Against::Attributes(32), ..P }, P], ..N }),
    // Cloudian - Eye of the Typhoon
    (57610714, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // The Wicked Eraser
    (57793869, Facts { attacked: [Attacked { attacker: Fate::Destroyed, collateral: ALWAYS, ..P }; 2], effect_collateral: ALWAYS, ..N }),
    // Mother Grizzly
    (57839750, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Nimble Musasabi
    (57844634, Facts { attacked: [Attacked { burn: Burn::Fixed(500), ..P }; 2], ..N }),
    // Evil HERO Malicious Edge
    (58554959, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Gaia Drake, the Universal Force
    (58601383, Facts { untargetable: kind::MONSTER, ..N }),
    // Nightmare Horse
    (59290628, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Jurrac Velo
    (59312550, Facts { attacked: [Attacked { payoff: 1000, ..P }, P], ..N }),
    // Ally Salvo
    (59482302, Facts { attacked: [Attacked { attacker: Fate::Destroyed, collateral: 1, against: Against::Attributes(16), ..P }; 2], ..N }),
    // Krebons
    (59575539, Facts { attacked: [Attacked { negates: ALWAYS, negate_cost: 800, ..P }; 2], ..N }),
    // Elemental HERO Bladedge
    (59793705, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Archfiend Zombie-Skull
    (59969392, Facts { immune: kind::ALL, ..N }),
    // Blizzed, Defender of the Ice Barrier
    (60161788, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Darkness Neosphere
    (60417395, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Elemental HERO Plasma Vice
    (60493189, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Naturia Cherries
    (60668166, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], effect_payoff: 1000, ..N }),
    // UFO Turtle
    (60806437, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Skull Archfiend of Lightning
    (61370518, Facts { negates_aimed: kind::ALL, negate_times: ALWAYS, ..N }),
    // Kazejin
    (62340868, Facts { attacked: [Attacked { attacker_atk: AtkChange::Zero, ..P }; 2], ..N }),
    // Arcana Force 0 - The Fool
    (62892347, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Rai-Mei
    (63223467, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], ..N }),
    // Goblin Zombie
    (63665875, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Gravekeeper's Spear Soldier
    (63695531, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Exarion Universe
    (63749102, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Submarine Frog
    (63948258, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Ojama Blue
    (64627453, Facts { attacked: [Attacked { payoff: 1400, ..P }; 2], ..N }),
    // Dark Driceratops
    (65287621, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Toon Mermaid
    (65458948, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Fiend Skull Dragon
    (66235877, Facts { negates_aimed: kind::TRAP, negate_times: ALWAYS, ..N }),
    // Fortress Warrior
    (66288028, Facts { attacked: [Attacked { survives: 1, no_damage: true, ..P }, Attacked { survives: 1, ..P }], ..N }),
    // Karakuri Strategist mdl 248 "Nishipachi"
    (66625883, Facts { attacked: [Attacked { switches: true, ..P }, P], ..N }),
    // Goblin Black Ops
    (66707058, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Majestic Red Dragon
    (67030233, Facts { immune: kind::ALL, ..N }),
    // Majioshaleon
    (67211766, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Meklord Emperor Wisel
    (68140974, Facts { negates_aimed: kind::SPELL, negates_destruction: kind::SPELL, negate_times: 1, ..N }),
    // Flamvell Dragnov
    (68226653, Facts { attacked: [Attacked { burn: Burn::Fixed(500), ..P }; 2], ..N }),
    // Stardust Xiaolong
    (68543408, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Elemental HERO Inferno
    (68745629, Facts { attacked: [Attacked { stat: 1000, against: Against::Attributes(2), ..P }, P], ..N }),
    // Blackwing Armor Master
    (69031175, Facts { attacked: [Attacked { survives: ALWAYS, no_damage: true, ..P }, Attacked { survives: ALWAYS, ..P }], ..N }),
    // Avenging Knight Parshath
    (69514125, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Volcanic Scattershot
    (69750546, Facts { attacked: [Attacked { burn: Burn::Fixed(500), ..P }; 2], ..N }),
    // Darksea Float
    (70054514, Facts { effect_payoff: 700, ..N }),
    // D.D. Assailant
    (70074904, Facts { attacked: [Attacked { attacker: Fate::Banished, leaves: true, ..P }; 2], ..N }),
    // Naturia Dragonfly
    (70083723, Facts { attacked: [Attacked { survives: ALWAYS, against: Against::AttackFrom(2000), ..P }; 2], ..N }),
    // Karakuri Watchdog mdl 313 "Saizan"
    (70271583, Facts { attacked: [Attacked { survives: 1, switches: true, ..P }, Attacked { switches: true, ..P }], ..N }),
    // Mucus Yolk
    (70307656, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Rescue Warrior
    (70630741, Facts { attacked: [Attacked { no_damage: true, ..P }, P], ..N }),
    // Dark General Freed
    (70676581, Facts { negates_aimed: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Thought Ruler Archfiend
    (70780151, Facts { negates_aimed: kind::SPELL | kind::TRAP, negate_times: ALWAYS, ..N }),
    // Ally of Justice Thunder Armor
    (71438011, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Troposphere
    (72144675, Facts { immune: kind::TRAP, unaffected: kind::TRAP, ..N }),
    // Koa'ki Meiru Valafar
    (72258771, Facts { striking: Striking { piercing: true, ..S }, immune: kind::TRAP, ..N }),
    // Silent Magician LV8
    (72443568, Facts { immune: kind::SPELL, unaffected: kind::SPELL, ..N }),
    // Dark Artist
    (72520073, Facts { attacked: [P, Attacked { stat: -700, against: Against::Attributes(16), ..P }], ..N }),
    // Chaos Command Magician
    (72630549, Facts { negates_aimed: kind::MONSTER, negate_times: ALWAYS, ..N }),
    // Silpheed
    (73001017, Facts { attacked: [Attacked { collateral: 1, ..P }; 2], ..N }),
    // Silent Swordsman LV5
    (74388798, Facts { immune: kind::SPELL, unaffected: kind::SPELL, ..N }),
    // Emissary of the Afterlife
    (75043725, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Snapdragon
    (75673220, Facts { attacked: [Attacked { collateral: 1, ..P }; 2], effect_collateral: 1, ..N }),
    // Mine Golem
    (76321376, Facts { attacked: [Attacked { burn: Burn::Fixed(500), ..P }; 2], ..N }),
    // Gem-Knight Ruby
    (76614340, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Enraged Battle Ox
    (76909279, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Blackwing Armed Wing
    (76913983, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Pyramid Turtle
    (77044671, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Inaba White Rabbit
    (77084837, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // XX-Saber Garsem
    (77330185, Facts { effect_payoff: 700, ..N }),
    // Red Dragon Archfiend/Assault Mode
    (77336644, Facts { striking: Striking { target: Fate::Destroyed, ..S }, ..N }),
    // Jinzo
    (77585513, Facts { negates_any: kind::TRAP, negate_times: ALWAYS, ..N }),
    // Cyberdark Edge
    (77625948, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Machina Peacekeeper
    (78349103, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Yubel
    (78371393, Facts { attacked: [Attacked { survives: ALWAYS, no_damage: true, burn: Burn::Reflected, ..P }, Attacked { survives: ALWAYS, ..P }], ..N }),
    // XX-Saber Fulhelmknight
    (78422252, Facts { attacked: [Attacked { negates: 1, ..P }; 2], ..N }),
    // Gigastone Omega
    (79080761, Facts { effect_collateral: 2, ..N }),
    // Black Stego
    (79409334, Facts { attacked: [Attacked { switches: true, ..P }, P], ..N }),
    // Lancer Archfiend
    (79418153, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // White Night Dragon
    (79473793, Facts { negates_aimed: kind::SPELL | kind::TRAP, negate_times: ALWAYS, ..N }),
    // Reptilianne Naga
    (79491903, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Injection Fairy Lily
    (79575620, Facts { attacked: [Attacked { stat: 3000, ..P }, P], striking: Striking { bonus: 3000, ..S }, ..N }),
    // Cloudian - Altus
    (79703905, Facts { attacked: [Attacked { survives: ALWAYS, ..P }, P], ..N }),
    // Mad Sword Beast
    (79870141, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Dark Balter the Terrible
    (80071763, Facts { negates_destruction: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Neo-Spacian Grand Mole
    (80344569, Facts { attacked: [Attacked { attacker: Fate::Returned, before_damage: true, leaves: true, ..P }; 2], striking: Striking { target: Fate::Returned, before_damage: true, leaves: true, ..S }, ..N }),
    // General Raiho of the Ice Barrier
    (81275309, Facts { negates_aimed: kind::MONSTER, negate_times: ALWAYS, ..N }),
    // Sword Master
    (81336148, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Wattpheasant
    (81896771, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Sphere of Chaos
    (82693042, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Mystic Tomato
    (83011277, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Grandmaster of the Six Samurai
    (83039729, Facts { effect_payoff: 700, ..N }),
    // Ancient Gear Golem
    (83104731, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Scrap Goblin
    (83135907, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Oyster Meister
    (83239739, Facts { effect_payoff: 300, ..N }),
    // Cloudian - Ghost Fog
    (83604828, Facts { attacked: [Attacked { no_damage: true, ..P }, P], ..N }),
    // Destiny HERO - Plasma
    (83965310, Facts { negates_aimed: kind::MONSTER, negate_times: 1, ..N }),
    // Cloudian - Poison Cloud
    (83982270, Facts { attacked: [Attacked { attacker: Fate::Destroyed, when_destroyed: true, burn: Burn::Fixed(800), ..P }; 2], ..N }),
    // Spell Canceller
    (84636823, Facts { negates_any: kind::SPELL, negate_times: ALWAYS, ..N }),
    // Flying Kamakiri #1
    (84834865, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Jurrac Titano
    (85028288, Facts { untargetable: kind::MONSTER, ..N }),
    // Card Trooper
    (85087012, Facts { attacked: [Attacked { payoff: 700, ..P }; 2], effect_payoff: 700, ..N }),
    // Reaper on the Nightmare
    (85684223, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], striking: Striking { direct: true, ..S }, ..N }),
    // Darklord Asmodeus
    (85771019, Facts { attacked: [Attacked { payoff: 600, ..P }; 2], effect_payoff: 600, ..N }),
    // Elemental HERO Wildheart
    (86188410, Facts { immune: kind::TRAP, unaffected: kind::TRAP, ..N }),
    // Garmr of the Nordic Beasts
    (88283496, Facts { attacked: [Attacked { attacker: Fate::Returned, against: Against::LevelBelow(5), ..P }; 2], ..N }),
    // Sorcerer of Dark Magic
    (88619463, Facts { negates_any: kind::TRAP, negates_aimed: kind::TRAP, negate_times: ALWAYS, ..N }),
    // Elemental HERO Shining Phoenix Enforcer
    (88820235, Facts { attacked: [Attacked { survives: ALWAYS, ..P }; 2], ..N }),
    // Familiar Knight
    (89731911, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Dewdark of the Ice Barrier
    (90311614, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Obsidian Dragon
    (90464188, Facts { negates_aimed: kind::SPELL | kind::TRAP, negate_times: ALWAYS, ..N }),
    // Black Ptera
    (90654356, Facts { effect_payoff: 700, ..N }),
    // Raging Flame Sprite
    (90810762, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Toon Dark Magician Girl
    (90960358, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // The Agent of Force - Mars
    (91123920, Facts { immune: kind::SPELL, unaffected: kind::SPELL, ..N }),
    // Toon Summoned Skull
    (91842653, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Morphtronic Boomboxen
    (92720564, Facts { attacked: [P, Attacked { negates: 1, ..P }], ..N }),
    // Howling Insect
    (93107608, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Spell Striker
    (93187568, Facts { attacked: [Attacked { no_damage: true, ..P }, P], striking: Striking { direct: true, ..S }, ..N }),
    // Driven Daredevil
    (93353691, Facts { attacked: [Attacked { survives: ALWAYS, attacker: Fate::Destroyed, ..P }, Attacked { survives: ALWAYS, attacker: Fate::Destroyed, against: Against::AttackFrom(2500), ..P }], ..N }),
    // Darkness Destroyer
    (93709215, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Karakuri Ninja mdl 339 "Sazank"
    (93724592, Facts { attacked: [Attacked { switches: true, ..P }, P], ..N }),
    // Amazoness Swords Woman
    (94004268, Facts { attacked: [Attacked { no_damage: true, burn: Burn::Reflected, ..P }, P], ..N }),
    // Mine Mole
    (94079037, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Frozen Fitzgerald
    (94515289, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Max Warrior
    (94538053, Facts { striking: Striking { bonus: 400, ..S }, ..N }),
    // Tyrant Dragon
    (94568601, Facts { negates_aimed: kind::TRAP, negate_times: ALWAYS, ..N }),
    // Mad Archfiend
    (94664694, Facts { attacked: [Attacked { switches: true, ..P }, P], striking: Striking { piercing: true, ..S }, ..N }),
    // Mecha-Dog Marron
    (94667532, Facts { attacked: [Attacked { burn: Burn::Fixed(1000), ..P }; 2], ..N }),
    // Giant Germ
    (95178994, Facts { attacked: [Attacked { burn: Burn::Fixed(500), payoff: 1000, ..P }; 2], ..N }),
    // Hyper Psychic Blaster
    (95526884, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Crystal Beast Topaz Tiger
    (95600067, Facts { striking: Striking { bonus: 400, ..S }, ..N }),
    // Majestic Mech - Goryu
    (95701283, Facts { striking: Striking { piercing: true, ..S }, ..N }),
    // Shining Angel
    (95956346, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Jain, Lightsworn Paladin
    (96235275, Facts { striking: Striking { bonus: 300, ..S }, ..N }),
    // Giant Rat
    (97017120, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], ..N }),
    // Dark Resonator
    (97021916, Facts { attacked: [Attacked { survives: 1, ..P }; 2], ..N }),
    // Red Nova Dragon
    (97489701, Facts { immune: kind::ALL, ..N }),
    // Clear Vice Dragon
    (97811903, Facts { immune: kind::ALL, ..N }),
    // Wattdragonfly
    (97885363, Facts { attacked: [Attacked { payoff: 1000, ..P }; 2], effect_payoff: 1000, ..N }),
    // Handcuffs Dragon
    (97904474, Facts { attacked: [Attacked { payoff: 500, ..P }; 2], ..N }),
    // Suijin
    (98434877, Facts { attacked: [Attacked { attacker_atk: AtkChange::Zero, ..P }; 2], ..N }),
    // Dark Paladin
    (98502113, Facts { negates_aimed: kind::SPELL, negates_destruction: kind::SPELL, negate_times: ALWAYS, negate_discards: true, ..N }),
    // Five-Headed Dragon
    (99267150, Facts { attacked: [Attacked { survives: ALWAYS, against: Against::Attributes(47), ..P }; 2], ..N }),
    // Submarineroid
    (99861526, Facts { striking: Striking { direct: true, ..S }, ..N }),
    // Naturia Exterio
    (99916754, Facts { negates_any: kind::SPELL | kind::TRAP, negates_aimed: kind::SPELL | kind::TRAP, negates_destruction: kind::SPELL, negate_times: ALWAYS, ..N }),
];
